document.open();
document.write("<div id=\"footer_back\">");
document.write("<div id=\"footer_upper\">");
document.write("<div id=\"block_a\">");
document.write("<a href=\"http://www.kyoritsugroup.co.jp/\" target=\"_blank\"><img src=\"../common/img/km_logo.png\" alt=\"\" width=\"427\" height=\"56\" border=\"0\" /></a></div>");
document.write("<div id=\"block_b\">");
document.write("<div id=\"foot_btn_seikyu\"><a href=\"https://secure.kyoritsugroup.co.jp/senior/form/top.html\" onclick=\"_gaq.push(['_link', this.href]); return false;\"><img src=\"../common/img/btn_seikyu_rollout.png\" alt=\"\" width=\"180\" height=\"48\" border=\"0\" /></a></div></div></div>");
document.write("<div id=\"footer_bottom\">【介護対応型住宅】　<a href=\"/toda/\">ドーミー戸田公園Levi</a>　<a href=\"/kitaayase/\">ドーミー北綾瀬</a>　<a href=\"/nakanoegota/\">ドーミー中野江古田</a>　　　【自立型住宅】 <a href=\"/johoku/\">ドーミー城北公園</a>　<a href=\"/sagamihara/\">ドーミー相模原</a>　<a href=\"/kotoni/\">ドーミー琴似Levi</a>　<br>　<a href=\"http://www.dormy-senior.com/sitemap.html\">サイトマップ</a>　　<a href=\"http://www.dormy-senior.com/privacy.html\">個人情報保護方針</a>");
document.write("<div class=\"margintop\">Copyright (c) 2013- Dormy Senior. All Rights Reserved.</div></div></div>");
document.close();